"""temp change datetime to string in pub time

Revision ID: a50957c42d8a
Revises: e77378577661
Create Date: 2025-12-01 19:25:52.588499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a50957c42d8a"
down_revision: Union[str, Sequence[str], None] = "e77378577661"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_articles",
        "published_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_articles",
        "published_date",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
