"""Create a baseline migrations

Revision ID: e77378577661
Revises:
Create Date: 2025-12-01 18:46:26.862303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e77378577661"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("logo_src", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_article_category_id"), "article_category", ["id"], unique=False
    )
    op.create_table(
        "raw_articles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("article_url", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("published_date", sa.DateTime(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_raw_articles_id"), "raw_articles", ["id"], unique=False)
    op.create_table(
        "summarized_articles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("updated_title", sa.String(), nullable=False),
        sa.Column("src_url", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("img_src", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_summarized_articles_id"), "summarized_articles", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_summarized_articles_id"), table_name="summarized_articles")
    op.drop_table("summarized_articles")
    op.drop_index(op.f("ix_raw_articles_id"), table_name="raw_articles")
    op.drop_table("raw_articles")
    op.drop_index(op.f("ix_article_category_id"), table_name="article_category")
    op.drop_table("article_category")
    # ### end Alembic commands ###
