"""bingo

Revision ID: f8425ce388ed
Revises: d1c866c6d4b2
Create Date: 2025-12-18 22:27:17.033220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8425ce388ed"
down_revision: Union[str, Sequence[str], None] = "d1c866c6d4b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "summarized_articles", sa.Column("updatedAt", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("summarized_articles", "updatedAt")
    # ### end Alembic commands ###
