"""memo

Revision ID: 0dea459dfbff
Revises: 3fde4a7c70c2
Create Date: 2025-12-18 14:07:47.811650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dea459dfbff'
down_revision: Union[str, Sequence[str], None] = '3fde4a7c70c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summarized_articles', 'img_src',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summarized_articles', 'img_src',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
