"""winter_cold_yellow_light

Revision ID: 3fde4a7c70c2
Revises: b1fcc760b872
Create Date: 2025-12-18 13:29:04.533486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fde4a7c70c2'
down_revision: Union[str, Sequence[str], None] = 'b1fcc760b872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summarized_articles', sa.Column('raw_article_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'summarized_articles', ['raw_article_id'])
    op.create_foreign_key(None, 'summarized_articles', 'raw_articles', ['raw_article_id'], ['id'])
    op.drop_column('summarized_articles', 'updatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summarized_articles', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'summarized_articles', type_='foreignkey')
    op.drop_constraint(None, 'summarized_articles', type_='unique')
    op.drop_column('summarized_articles', 'raw_article_id')
    # ### end Alembic commands ###
