"""update fields

Revision ID: b1fcc760b872
Revises: a50957c42d8a
Create Date: 2025-12-18 13:18:09.322505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fcc760b872'
down_revision: Union[str, Sequence[str], None] = 'a50957c42d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summarized_articles', sa.Column('title', sa.String(), nullable=False))
    op.add_column('summarized_articles', sa.Column('article_url', sa.String(), nullable=False))
    op.add_column('summarized_articles', sa.Column('source', sa.String(), nullable=False))
    op.add_column('summarized_articles', sa.Column('published_date', sa.String(), nullable=False))
    op.add_column('summarized_articles', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('summarized_articles', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'summarized_articles', 'article_category', ['category_id'], ['id'])
    op.drop_column('summarized_articles', 'updated_title')
    op.drop_column('summarized_articles', 'src_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summarized_articles', sa.Column('src_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('summarized_articles', sa.Column('updated_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'summarized_articles', type_='foreignkey')
    op.alter_column('summarized_articles', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('summarized_articles', 'category_id')
    op.drop_column('summarized_articles', 'published_date')
    op.drop_column('summarized_articles', 'source')
    op.drop_column('summarized_articles', 'article_url')
    op.drop_column('summarized_articles', 'title')
    # ### end Alembic commands ###
