INDIA_TODAY_HOME = "https://www.indiatoday.in/rss/home"
THE_HINDU_DEFAULT_HOME = "https://www.thehindu.com/feeder/default.rss"
TIMES_OF_INDIA_HOME = "https://timesofindia.indiatimes.com/"
TOI_TOP_STORIES = "rssfeedstopstories.cms"
THE_HINDU_DEFAULT_HOME = "https://www.thehindu.com/feeder/default.rss"
BBC_HOME = "https://feeds.bbci.co.uk/news/rss.xml"
